"""removed rows from the task model

Revision ID: 03904f48d129
Revises: dda7b9e0cba2
Create Date: 2025-07-31 17:50:30.323776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03904f48d129'
down_revision = 'dda7b9e0cba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.drop_column('color_meaning')
        batch_op.drop_column('repeat_group_id')
        batch_op.drop_column('repeat')
        batch_op.drop_column('comments')
        batch_op.drop_column('category')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('due_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_datetime', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('repeat', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('repeat_group_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('color_meaning', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
