"""altar duration to end_date_time

Revision ID: 1a50cfc389dd
Revises: 03904f48d129
Create Date: 2025-09-06 00:08:09.718861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a50cfc389dd'
down_revision = '03904f48d129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))
        batch_op.drop_column('end_date_time')

    # ### end Alembic commands ###
