"""add content column in task model

Revision ID: 918aa5c56768
Revises: dd0a6702814c
Create Date: 2025-07-18 19:56:33.737128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918aa5c56768'
down_revision = 'dd0a6702814c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
