"""Add repeat, comments, color, and color meaning to Task

Revision ID: dd0a6702814c
Revises: 669b861449ef
Create Date: 2025-07-16 11:05:05.231090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0a6702814c'
down_revision = '669b861449ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color_meaning', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('repeat', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('repeat')
        batch_op.drop_column('color_meaning')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
