"""repeat_group_id added to task model

Revision ID: dda7b9e0cba2
Revises: f1afbe75181d
Create Date: 2025-07-27 10:57:35.234593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda7b9e0cba2'
down_revision = 'f1afbe75181d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_group_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('repeat_group_id')

    # ### end Alembic commands ###
